### ISSUE TITLE
has_one, has_many associations seem not working

### ISSUE THREAD

**Issue by tokichie** [rom-rb/rom-factory#20]
I found that `has_one` and `has_many` associations didn't work properly.
In this reproduction code, `has_many` is used, but `has_one` results in the same.
I traced into rom-factory and dry, but there was no idea about the root cause.

**Steps for Reproduction**
```ruby
require 'rom'
require 'rom-factory'

rom = ROM.container(:sql, 'sqlite::memory') do |conf|
  conf.default.create_table(:companies) do
    primary_key :id
    column :name, String, null: false
  end

  conf.default.create_table(:users) do
    primary_key :id
    column :name, String, null: false
    column :company_id, Integer, null: false
  end

  conf.relation(:companies) do
    schema(:companies, infer: true) do
      associations do
        has_many :users
      end
    end
  end

  conf.relation(:users) do
    schema(:users, infer: true) do
      associations do
        belongs_to :companies, as: :company
      end
    end
  end
end

MyFactory = ROM::Factory.configure do |c|
  c.rom = rom
end

MyFactory.define(:company) do |f|
  f.name { fake(:company, :name) }
  f.association(:users, count: 2)
end

MyFactory.define(:user) do |f|
  f.name { fake(:name) }
  f.association(:company)
end

p MyFactory.structs[:user]
p MyFactory.structs[:company]
```

**Expected behavior**:
```
#<ROM::Struct::User id=1 name="Emmet Koss" company_id=1 company=#<ROM::Struct::Company id=1 name="Heaney, Wilkinson and Senger">>
#<ROM::Struct::Company id=1 name="Acme Inc" users=[#<ROM::Struct::User id=1 name="Emmet Koss" company_id="1">, #<ROM::Struct::User id=2 name="Bryce Lehner" company_id="1">]>
```

**Actual behavior**:
```
#<ROM::Struct::User id=1 name="Emmet Koss" company_id=1 company=#<ROM::Struct::Company id=1 name="Heaney, Wilkinson and Senger">>
Traceback (most recent call last):
	12: from assoc_test.rb:48:in `<main>'
	11: from /Users/tokitake/workspace/rom/vendor/bundle/ruby/2.5.0/gems/rom-factory-0.6.0/lib/rom/factory/factories.rb:43:in `[]'
	10: from /Users/tokitake/workspace/rom/vendor/bundle/ruby/2.5.0/gems/rom-factory-0.6.0/lib/rom/factory/builder.rb:30:in `struct'
	 9: from /Users/tokitake/workspace/rom/vendor/bundle/ruby/2.5.0/gems/rom-factory-0.6.0/lib/rom/factory/tuple_evaluator.rb:34:in `struct'
	 8: from /Users/tokitake/workspace/rom/vendor/bundle/ruby/2.5.0/gems/dry-struct-0.4.0/lib/dry/struct/class_interface.rb:95:in `new'
	 7: from /Users/tokitake/workspace/rom/vendor/bundle/ruby/2.5.0/gems/dry-types-0.12.2/lib/dry/types/constructor.rb:47:in `call'
	 6: from /Users/tokitake/workspace/rom/vendor/bundle/ruby/2.5.0/gems/dry-types-0.12.2/lib/dry/types/hash/schema.rb:27:in `call'
	 5: from /Users/tokitake/workspace/rom/vendor/bundle/ruby/2.5.0/gems/dry-types-0.12.2/lib/dry/types/hash/schema.rb:97:in `coerce'
	 4: from /Users/tokitake/workspace/rom/vendor/bundle/ruby/2.5.0/gems/dry-types-0.12.2/lib/dry/types/hash/schema.rb:110:in `resolve'
	 3: from /Users/tokitake/workspace/rom/vendor/bundle/ruby/2.5.0/gems/dry-types-0.12.2/lib/dry/types/hash/schema.rb:110:in `each'
	 2: from /Users/tokitake/workspace/rom/vendor/bundle/ruby/2.5.0/gems/dry-types-0.12.2/lib/dry/types/hash/schema.rb:112:in `block in resolve'
	 1: from /Users/tokitake/workspace/rom/vendor/bundle/ruby/2.5.0/gems/dry-types-0.12.2/lib/dry/types/hash/schema.rb:99:in `block in coerce'
 /Users/tokitake/workspace/rom/vendor/bundle/ruby/2.5.0/gems/dry-types-0.12.2/lib/dry/types/array/member.rb:20:in `call': undefined method `map' for #<Proc:0x00007fb77731e698> (NoMethodError)
Did you mean?  tap
```

**Platforms**:
macOS 10.13.3
ruby 2.5.0

**Version**:
rom 4.1.3
rom-factory 0.6.0

**Comment by GustavoCaso** [comment]
Hi, @tokichie thank you for submitting the issue ❤️ . I'm investigating, but as a quick fix instead of using `MyFactory.structs[:company]` you use `MyFactory[:company]` it will work.

Looks like we are not resolving correctly the relations when using structs, I will dig a little to see if we could resolve the issue.

**Comment by solnic** [comment]
oh, in-memory `structs` don't support associations **at all**. sorry about the confusion
