### ISSUE TITLE
Argument error could be more informative

### ISSUE THREAD

**Issue by andrewcroome** [rom-rb/rom-factory#23]
I recently managed to create a join table for image attachments on news items in which I failed to define a primary key like the below:

`primary_key [:news_item_id, :asset_id]`

The first sign of my mistake was rom-factory raising the following error when calling the relation's factory:

```
ArgumentError:
       ROM::Relation::Combined#by_pk arity is 1 (0 args given)
```

I was able to find my mistake with help from @timriley, but I wonder if we could add mention to that error to check one's primary key as a pointer to others?

The top of the stacktrace was:

```
/Users/andrewcroome/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rom-core-4.2.0/lib/rom/relation/curried.rb:73:in `to_a'
/Users/andrewcroome/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rom-core-4.2.0/lib/rom/relation/materializable.rb:55:in `first'
/Users/andrewcroome/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rom-factory-0.6.0/lib/rom/factory/builder/persistable.rb:31:in `create'
```

**Comment by timriley** [comment]
Thinking we could raise our own error if `pk` in https://github.com/rom-rb/rom-factory/blob/ee2462f9ee52e3756369c7dfbd56d0b8370dd9b9/lib/rom/factory/builder/persistable.rb#L29 is empty.
